version: '2'
services:
  bibliotheque-app:
    image: bibliotheque
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bibliotheque-postgresql:5432/Bibliotheque
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  bibliotheque-postgresql:
    extends:
      file: postgresql.yml
      service: bibliotheque-postgresql
